[features]
seeds = false
[programs.devnet]
votesol = "HWFFMkkxfV2xSpxytZQaEDP1QCYLKG71Vxt7bZ6zgFhK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/ishan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
